### ISSUE TITLE
Dispensers incorrectly dispensing metal

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#10]
Original report: http://steamcommunity.com/groups/TF2Classic2015/discussions/2/613948093873318661/

"The green one gives metal to blue engineers and the yellow one gives it to red engineers. I have not yet tested this with regular ammo or health though.
The yellow dispenser also has the same screen as the green one, which I assume is a bug too and not a placeholder."

**Comment by danielmm8888** [comment]
The dispenser color bug has been fixed. I also may have fixed the team bug too, however I need to do a bit more testing first.
