### ISSUE TITLE
Game crashes on startup [SOLVED]

### ISSUE THREAD

**Issue by gamerscruffy** [danielmm8888/TF2Classic#101]
I did everything. Exported everything in the .rar into a tf2classic foldier in sourcemods. But after it is done loading when I start it up, it crashes. Am I doing something wrong? I installed the Source SDK 2013 Multiplayer. And set it to upcoming.

**Comment by PistonMiner** [comment]
First of all, what version did you download? We don't distribute versions via RAR files. We distribute them via 7Z files, so its likely you downloaded a wrong version.
