### ISSUE TITLE
Crash after sellecting class

### ISSUE THREAD

**Issue by maxxy11** [danielmm8888/TF2Classic#13]
After joining a server and picking a team I tried to choose a class but when ever I sellect any of them the game crashes. Before crashing I spawned in and seen the viewmodel drawing animatinon and its first frames (the hands) and then the game suddenly crashes.

**Comment by 404UserNotFound** [comment]
If I recall correctly, while conversating with Maxxy, he informed me that he fixed this by installing the latest patch.
