### ISSUE TITLE
Killfeed - Assister teamcolor suggestion

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#14]
![killfeedassistcolors](https://cloud.githubusercontent.com/assets/5123258/5916889/6c62bfe2-a5e4-11e4-82a0-2cde873eaf14.jpg)

Notice I am on GRN, yet my assist name in the killfeed reverts to RED.

Ideally, the + symbol should be the default black/white color based on the killfeed background color, and then the assister name should be in proper team color.

**Comment by danielmm8888** [comment]
This will be fixed in the next update.
