### ISSUE TITLE
dm_compound has world holes

### ISSUE THREAD

**Issue by GrandpaSpud** [danielmm8888/TF2Classic#142]
dm_compound has 2 big world holes that get you stuck in them
![2015-08-19_00003](https://cloud.githubusercontent.com/assets/6463144/9364249/10668cde-46b4-11e5-9b1a-9f9b393535f8.jpg)
![2015-08-19_00004](https://cloud.githubusercontent.com/assets/6463144/9364253/134898e8-46b4-11e5-8a51-ae11c5c2b680.jpg)

**Comment by danielmm8888** [comment]
Thank you for reporting the issue, however dm_compound has been removed in 2.0.
