### ISSUE TITLE
Stickybomb "charging" sound plays all the way

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#16]
Yeah, when you tap to fire the sticky bomb launcher instead of charging a shot, the sound plays the whole way through.

Rapid tapping results in it stopping and re-starting until you stop, in which case it fully plays the sound.

**Comment by 404UserNotFound** [comment]
Here's a video of the issue. Oddly doesn't happen sometimes.

https://www.youtube.com/watch?v=Tt6i2qv0yMI

**Comment by danielmm8888** [comment]
Fixed
