### ISSUE TITLE
Scout Nailgun world anim weirdness still exists

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#160]
Crouch-walk left while holding the Nailgun and note the gap in his walk. I remember that being an issue since before 1.9

**Comment by danielmm8888** [comment]
We've just now fixed the crouch anims. Thanks for reporting the bug

**Comment by 404UserNotFound** [comment]
Actually, there are no proper crouch-walk anims in thirdperson. They all utilize the Scattergun "holding" positions of the hands and switch back to the new Nailgun hand positions when you stop crouch-walking and just crouch.

And I'm not sure what can be done about this, but thirdperson reloading doesn't match firstperson reloading. Maybe we could keep the existing reload anim but have the Scout seemingly take the nail barrel off during the anim.
