### ISSUE TITLE
Probably-known-about ingame loadout issue

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#165]
When viewing the Medic's items on the ingame "m" button loadout menu, the third medigun is outside the bounds. Perhaps that menu should be resized (or just get rid of it and make "m" bring up the main menu's loadout menu).

I'd also look into switching the skin of the 3d player model based on what team the player is currently on when ingame, instead of having it be Red all the time.

**Comment by danielmm8888** [comment]
Have you deleted your old files before copying the new one over? The old in-game loadout menu has been scrapped and replaced by the new one already. If you've got clean files it should automatically bind it to that.

**Comment by 404UserNotFound** [comment]
Whoops, seems this was for 1.9 and I got confused. Feel free to close this :P

**Comment by 404UserNotFound** [comment]
Though the skin thing for the new loadout menu would be a great addition.

**Comment by MrModez** [comment]
Thanks for the skin suggestion, it will be added in the next patch.
