### ISSUE TITLE
Arena_offblast_final invisible wall

### ISSUE THREAD

**Issue by Toxic10** [danielmm8888/TF2Classic#166]
In the arena_offblast_final in this one hallway on the side of the map you cant go trough it in if you come from the blue team spawn side

**Comment by iiboharz** [comment]
Yeah - this is my fault.

I ended up accidentally placing a clip brush in that hallway and compiled the map without realizing, we only figured this out once the client was packaged for distribution.

There's not much we can do at this point unless we release a patch.

**Comment by danielmm8888** [comment]
This has been fixed in the next version.
