### ISSUE TITLE
Dominate and revenge text in DM is black

### ISSUE THREAD

**Issue by RaraFolf** [danielmm8888/TF2Classic#167]
As the title says.

Example of what I mean:
![image](https://cloud.githubusercontent.com/assets/11066571/9578438/0ec0c91e-4fb8-11e5-8eaa-bf034238c261.png)

**Comment by RaraFolf** [comment]
Also, could you please put a time limit on the color changes in-game?
Because people with superfast swtiching colors hurts the eyes (like SolarLight there was ever other frame either pink or lime green)

**Comment by AgentAgrimar** [comment]
Don't be surprised when I come on spamming Starman sound spray while changing colors every 0.1 frame. :+1:

**Comment by danielmm8888** [comment]
This isn't a bug. The domination and revenge text is supposed to be black, just like in live TF2.

**Comment by NicknineTheEagle** [comment]
I'm pretty sure he means player names are black instead of using player's merc color.

**Comment by danielmm8888** [comment]
This has been fixed in the next version.
