### ISSUE TITLE
Cloaked spy is still missing texture

### ISSUE THREAD

**Issue by RaraFolf** [danielmm8888/TF2Classic#168]
This is a pic from 1.8:
![2015-04-10_00001](https://cloud.githubusercontent.com/assets/11066571/9583330/bd16abee-4fd8-11e5-8a17-ddd8a98ac1b5.jpg)

And here is the 2.0 Beta:
![2015-08-31_00001](https://cloud.githubusercontent.com/assets/11066571/9583336/c389c718-4fd8-11e5-85ee-3959f767e87a.jpg)

Why is this still happening?

**Comment by PartyDude** [comment]
Id suggest reinstalling, except disable your antivirus before you reinstall

**Comment by NicknineTheEagle** [comment]
Fixed a long time ago, I assume.
