### ISSUE TITLE
Weapon Switch Issue

### ISSUE THREAD

**Issue by sylvee** [danielmm8888/TF2Classic#169]
In Deathmatch, if you press q to switch to your previous weapon (i.e. Sten to SMG), you can instantly shoot without waiting for the 0.67 second delay when you switch to your secondary or primary, as if you had instant weapon switching active (like the Agility powerup in Mannpower on TF2 live). Some weapons aren't affected by this however, like the Shotgun.

**Comment by RaraFolf** [comment]
This also happens in normal matches, like a Scout with the nailgun and Sten can do that as well.

**Comment by danielmm8888** [comment]
This has been fixed in the next version.
