### ISSUE TITLE
i don't see any servers

### ISSUE THREAD

**Issue by maxdeelb4** [danielmm8888/TF2Classic#177]
there was no server in the game probably a glitch or something could you tell me how to fix it

**Comment by danielmm8888** [comment]
Please watch this video, it gives a nice explanation of the issue

https://www.youtube.com/watch?v=AMejFTgzGMk&app=desktop

**Comment by danielmm8888** [comment]
A more in-depth explanation is that when Valve decided to release the new beta-test branch for Source 2013 MP base, it seems to have caused a bug where the Steam Master Server rejects any server running on that branch. The master server reports that the server is out of date. This seems to happen with any Source 2013 MP Base mod running on the beta-test branch.

We've been waiting on Valve to fix the issue for at least 2 months now, however they haven't been replying to any of our emails.

**Comment by maxdeelb4** [comment]
understood

**Comment by maxdeelb4** [comment]
thanks

**Comment by Th13teen** [comment]
This has now been fixed.
