### ISSUE TITLE
Beta Muzzleflash

### ISSUE THREAD

**Issue by dreyburn** [danielmm8888/TF2Classic#18]
The beta muzzleflash needs work in a few areas.

First off, the effect model should spin with the same speed as the minigun, as seen in this video: https://www.youtube.com/watch?v=jHgZh4GV9G0

I don't think the beta muzzle flash should be added to all the weapons, unless it's scaled properly or a particle-based fix is implemented

**Comment by danielmm8888** [comment]
I have already added a keyvalue for the weapons called "MuzzleFlashModelScale' which can be set in each weapon file separately, however to this day nobody has done anything with it.
