### ISSUE TITLE
Missing data for object "OBJ_DISPENSER"  in scripts/objects.txt

### ISSUE THREAD

**Issue by Msalinas2877** [danielmm8888/TF2Classic#192]
When i compile the master branch, copy all the files and try to run the game i get that error and i have objects.txt

**Comment by danielmm8888** [comment]
Are you absolutely sure that you have the objects.txt file from the master branch? The 2.0.0b1 objects.txt file isn't compatible with the current code.

**Comment by Msalinas2877** [comment]
Yes i am sure
[objects.txt](https://github.com/danielmm8888/TF2Classic/files/41121/objects.txt)

**Comment by Msalinas2877** [comment]
what i am doing wrong?

**Comment by danielmm8888** [comment]
Try this file
http://pastebin.com/D7LCxnUZ

**Comment by Msalinas2877** [comment]
fixed that thanks, but now the game just freeze
