### ISSUE TITLE
[Linux] Mouse cursor issue

### ISSUE THREAD

**Issue by fwinest-JediThug** [danielmm8888/TF2Classic#193]
Trying to move the mouse cursor resets it to the middle of the screen after a certain distance, which makes it impossible to use w/ a 16:9 resolution (1366x768). When using a 4:3 resolution (1024x768), the main menu entries are selectable, but e.g. selecting a button like "Apply" in the options menu is impossible.

Video: http://webmshare.com/1LE1P

Kubuntu 15.10

**Comment by danielmm8888** [comment]
Could you try typing cl_software_cursor 0 in the console and see whether the issue still persists?

**Comment by fwinest-JediThug** [comment]
This fixed the problem! Maybe having this as the default would be great,
since I've seen a couple of people on an image board who wanted to try the
game and had the same problem.

2015-11-23 12:32 GMT+01:00 danielmm8888 <notifications@github.com>:

**Comment by danielmm8888** [comment]
Glad to hear it. 
We've set that ConVar to 0 by default in the next release.
