### ISSUE TITLE
Friendly Spy Issue

### ISSUE THREAD

**Issue by PootisMentleGen** [danielmm8888/TF2Classic#195]
When you see a team spy, they appear as if STILL a spy, but on a diff. team. I was on YLW and a friendly spy (we spychecked him first) and he looked like a BLUE spy, but he was actually YLW.

**Comment by Th13teen** [comment]
This is a known problem,

Someone correct me if I'm wrong but if I'm correct its due to the texture limits on the model and due to the extra team skins we don't have enough for the mask(s) too. We're moving the mask to a cosmetic item for this reason.

**Comment by NicknineTheEagle** [comment]
Fixed for the next version. Spy mask has been separated from spy model. https://github.com/danielmm8888/TF2Classic/commit/74a6827872c95c4b877e153e901860394ae17e63
