### ISSUE TITLE
Starting Menu Cannot Drag Mouse Pointer Outside Circular Radius (2.0.0 Beta 1)

### ISSUE THREAD

**Issue by gitgud-software** [danielmm8888/TF2Classic#206]
I just grabbed TF2 Classic to try out for myself, but I'm running into trouble with just navigating the main menu.

The cursor can be moved, but if it moves outside an invisible circle located in the center of the menu the cursor will jump back to the center of the display.

My game is starting in fullscreen by default, because of this bug I have not been able to adjust any configurations.

I'm using Ubuntu GNOME 15.10 (wily), and I am playing the OpenGL, GNU/Linux native version of TF2Classic in fullscreen when I encounter this bug. I have attempted to move the cursor with both my laptop's trackpad on mouse. Whether both are configured as active on the same Desktop Environment or individually without the other present, the bug persists.

**Comment by danielmm8888** [comment]
Try entering cl_software_cursor 0 into the console

**Comment by danielmm8888** [comment]
And if your console isn't enabled, launch the game using the -console parameter

**Comment by gitgud-software** [comment]
Yeah, that did the trick for fixing the cursor. Thanks.
