### ISSUE TITLE
Multiclass weapons break on class change

### ISSUE THREAD

**Issue by zxz41** [danielmm8888/TF2Classic#234]
When you switch to a class with the same weapon equiped. The slot position and animations break.

![2016-01-13_00008 2](https://cloud.githubusercontent.com/assets/11709919/12300970/04b4de12-ba1e-11e5-8610-d797d3651a63.jpg)
![2016-01-13_00010 2](https://cloud.githubusercontent.com/assets/11709919/12300975/097c6b7c-ba1e-11e5-9e56-2595fee8c8a0.jpg)
![items_slot_breaking](https://cloud.githubusercontent.com/assets/11709919/12301032/4cc0c626-ba1e-11e5-868f-66f30e215309.jpg)

**Comment by NicknineTheEagle** [comment]
We don't have mult-class weapons, though (except for Gunboats). But this can be fixed.

**Comment by Yushe** [comment]
@NicknineTheEagle isn't the shotgun a multiclass weapon?

**Comment by NicknineTheEagle** [comment]
Yes, but stock shotgun uses different item IDs for every class.

**Comment by bmk10** [comment]
should be somewhere between ::SetModel and BoneMerge around the viewmodel code.

**Comment by NicknineTheEagle** [comment]
Fixed for the next version. https://github.com/danielmm8888/TF2Classic/commit/30926292142272ed91bf8ccc3ebde12443c8519e
