### ISSUE TITLE
Percentage calculations is wrong

### ISSUE THREAD

**Issue by zxz41** [danielmm8888/TF2Classic#235]
As seen on #234. Percentage calculations isn't rounding up numbers correctly.

![ammo_incorrect](https://cloud.githubusercontent.com/assets/11709919/12301229/33ba01fa-ba1f-11e5-9190-1352e1a56586.jpg)
```
"clip size bonus"
{
	"attribute_class"	"mult_clipsize"
	"value" "1.33"
}
```

**Comment by NicknineTheEagle** [comment]
6 * 1.33 = 7.98
Floats are normally rounded down when converted to integer. Live TF2 must be doing special rounding for clip size.

**Comment by NicknineTheEagle** [comment]
Fixed for the next version. https://github.com/danielmm8888/TF2Classic/commit/778a234c4418dbe0050bc5dc8f8fefee0e2e5784
