### ISSUE TITLE
Mysterious flying purple and black box.

### ISSUE THREAD

**Issue by zxz41** [danielmm8888/TF2Classic#236]
This took me waaaaay too long to recreate. Basicly hitting a friendly sticky (in this case with a melee) causes this really weird missing texture box to come flying past the screen like a UFO... Not even kidding.

![cp_well0000](https://cloud.githubusercontent.com/assets/11709919/12304250/d5ebb46e-ba2e-11e5-96fd-cf8deda74625.jpg)

I'll see if I can record it at some point

EDIT: I had to take the screenshot with host_timescale at ~0.25 just to be able to get a screenshot of it
EDIT 2: Seems to appear anywhere on well. Haven't tried other maps.

**Comment by danielmm8888** [comment]
Does the console print out any errors about a missing material?

**Comment by zxz41** [comment]
None. Even with -dev parameters

**Comment by Deathreus** [comment]
Doesn't explain why the box flies around even if the texture was there

**Comment by zxz41** [comment]
I have no clue why this is happening

**Comment by zxz41** [comment]
@danielmm8888 
Update: I found the issue. It have something to do with swing_b going back to idle
![image](https://cloud.githubusercontent.com/assets/11709919/12361106/6fd6cddc-bbbc-11e5-99e2-fcf7e9490aac.png)
Gotcha

**Comment by danielmm8888** [comment]
Fixed in the next ver. Thanks.
