### ISSUE TITLE
Randomizer is broken

### ISSUE THREAD

**Issue by Yushe** [danielmm8888/TF2Classic#244]
If randomizer is enabled the hand models will not appear.

**Comment by NicknineTheEagle** [comment]
How did you even enable randomizer in the first place? The cvar is supposed to be hidden.

**Comment by NicknineTheEagle** [comment]
https://github.com/danielmm8888/TF2Classic/blob/master/src/game/server/tf/tf_player.cpp#L108
Odd, I clearly remember adding FCVAR_DEVELOPMENTONLY flag.

**Comment by Yushe** [comment]
@NicknineTheEagle People find things
