### ISSUE TITLE
TF2C Engine Error

### ISSUE THREAD

**Issue by TheOpt1onal** [danielmm8888/TF2Classic#256]
When I tried to start TF2C for the first time, it loaded all the way to showing me one frame of the main menu before crashing. It then said 'Engine Error'. When I tried to open it again, it said I needed to update/verify Source SDK Base 2013 Multiplayer. When I verified it, it simply crashed again, showing me the 'Engine Error' message, and telling me to update/verify the SDK again.

**Comment by TheOpt1onal** [comment]
![capture1](https://cloud.githubusercontent.com/assets/19254674/15099935/c51ae870-1529-11e6-9a08-1f524d5cba7f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19254674/15099936/c51dc00e-1529-11e6-85e5-cda63617259c.PNG)

**Comment by danielmm8888** [comment]
Re-read the installation instructions.
http://tf2classic.com/install.php
