### ISSUE TITLE
Question about the freeze cam.

### ISSUE THREAD

**Issue by StrikerMan780** [danielmm8888/TF2Classic#257]
I know this isn't really an issue or bug report, but I'm not sure where else to post.

I'm currently working on a mod for HL2DM, and I'm wondering, how did you get the freezecam working correctly? I've tried many times, but I've had no luck. I've tried executing StartObserverMode( OBS_MODE_FREEZECAM ), in PlayerDeathThink but had no luck.

I've also tried setting the observer target on death, the target is apparently valid, but when I execute StartObserverMode, it doesn't change observer mode correctly. (I can tell it doesn't, I added an IF check for OBS_MODE_FREEZECAM with GetObserverMode after executing StartObserverMode just to be sure).

Keep in mind, I'm working from a base Source SDK 2013. If someone with knowledge can get it to work with that as a base, please, let me know. Perhaps it can be posted as a tutorial on the Valve Developer Wiki.

**Comment by bmk10** [comment]
I would suggest looking at the 2007 leak, and also running the debugger, making sure values are right client/server side.

I'll get it to work soon. its on my que for my mod. anyway, google StartObserverMode and site:github.com StartObserverMode and site:github.com OBS_MODE_FREEZECAM

**Comment by StrikerMan780** [comment]
Would that be this one? https://github.com/LestaD/SourceEngine2007

**Comment by StrikerMan780** [comment]
I looked it over, even tried migrating most of the code from that Source Engine 2007 repository, but something prevents the spectator mode from being set properly, not sure what.

**Comment by Yushe** [comment]
@StrikerMan780 Why don't you use a different version of the source engine?

**Comment by StrikerMan780** [comment]
What other version of source engine? I'm not *using* source engine 2007. I was just looking through the leaked source 2007 source code.

**Comment by PistonMiner** [comment]
This is really not the right place to post this. You should post it over on the [Source SDK 2013 repo](https://github.com/ValveSoftware/source-sdk-2013/) or the VDC as this is not an issue with or a question about TF2C.
