### ISSUE TITLE
Poacher's Pride visible when scoped

### ISSUE THREAD

**Issue by LUModder** [danielmm8888/TF2Classic#28]
When you scope in the gun, the gun is visible in the top corner.
![image](https://cloud.githubusercontent.com/assets/1606710/6678328/e30eb6c4-cbfe-11e4-9eee-97e64a48f459.png)

May only be with resolutions of 1080p and bigger.

**Comment by zxz41** [comment]
rip

**Comment by EmilSayahi** [comment]
This is caused because they increase the FOV when zooming in. When too zoomed in, view-models go to the top. Maybe they just didn't plan out how the zoom would work.

**Comment by EmilSayahi** [comment]
Maybe it's this line causing the issue: https://github.com/danielmm8888/TF2Classic/blob/62af8c0216a597a88521b41cfed68a83423dc4ea/src/game/shared/tf/tf_weapon_hunterrifle.cpp#L390

**Comment by PistonMiner** [comment]
Hilariously out of date.

**Comment by NicknineTheEagle** [comment]
This bug is still a thing, you know.

**Comment by NicknineTheEagle** [comment]
Confirming that it's visible with 90 FOV.

**Comment by PistonMiner** [comment]
This is a different issue than the one referenced at the time the issue was opened. See #258.
