### ISSUE TITLE
Disconnected: server uses different class tables

### ISSUE THREAD

**Issue by Play3rBust3r** [danielmm8888/TF2Classic#283]
![tf2 classic bug](https://cloud.githubusercontent.com/assets/29042681/26551518/46af4dfc-4483-11e7-844d-9fbf558ba92e.PNG)

How to fix this?

**Comment by danielmm8888** [comment]
You are most likely trying to join a server hosting a private beta, or
you're using an old public version.

Either way, this repo is no longer maintained and has been privatized.

**Comment by Play3rBust3r** [comment]
i installed

**Comment by Play3rBust3r** [comment]
i used the official server
