### ISSUE TITLE
Next Version?

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [danielmm8888/TF2Classic#285]
hello i'm want to know if there's will be a new version to TF2 Classic or just have a slow Developing?

**Comment by danielmm8888** [comment]
This repo is no longer maintained. The development has moved to a private closed repo.

**Comment by xXxToxicBlueDustxXx** [comment]
I have some curiosity and I would like to know, why was all the code moved to a private repo?

**Comment by danielmm8888** [comment]
I have no idea. I stopped working on this in January of 2016.

**Comment by xXxToxicBlueDustxXx** [comment]
What a bad thing :( I thought they work on a new update, good luck bro in your future projects I will be attentive in case there is any news

**Comment by danielmm8888** [comment]
They are working on a new update, they're just hiding everything from the public. They have a few special people and beta testers that they show the content to, but that's it. They have completely gotten rid of the community aspect of tf2c.

**Comment by xXxToxicBlueDustxXx** [comment]
Does it mean it's closed-source like TF2?

**Comment by Yushe** [comment]
@xXxToxicBlueDustxXx Yes, that's exactly what it means.

**Comment by raenii** [comment]
@Yushe that really sucks. 
@danielmm8888 the community aspect is gone? well, the games ruined.

**Comment by danielmm8888** [comment]
TF2C will eventually be open sourced again as the team moves onto developing TDC. I do not work on TF2C or TDC so I'm not sure of the exact release dates.

**Comment by raenii** [comment]
@danielmm8888 well, [the website](tf2classic.com) recently changed to say 'opening soon', so maybe relatively soon?
