### ISSUE TITLE
Some maps or servers are set to 1v1 only.

### ISSUE THREAD

**Issue by GintokiSakata** [danielmm8888/TF2Classic#33]
I don't know if it is the maps or something serverside but some maps (only tested dm_compound and ctf_well so far) only allow 1v1.

Played on vaultf4 and tf2classic UK,

**Comment by mattconsto** [comment]
Same issue here, the only maps working for me are cp_hydro_test1 (Which kind of sucks as it is impossible to win), blockfortress_a5 and ctf_4grounds.
