### ISSUE TITLE
Different Class Tables

### ISSUE THREAD

**Issue by mrchef** [danielmm8888/TF2Classic#38]
Whenever I try to join a server it rejects me saying something about classes and tables.

**Comment by danielmm8888** [comment]
Are you sure that you're on version 1.8.3?

**Comment by mrchef** [comment]
merde, I got 1.8.2 ;|

**Comment by Mudley** [comment]
We should really put the most recent version of the client on the main download link...

**Comment by danielmm8888** [comment]
And done

**Comment by mrchef** [comment]
Well, I got the 1.8.3 in and it still has that damned class problem...

**Comment by mrchef** [comment]
Welp, the problem is now that I have know clue how to get it in, by it I mean the Hotfix 1....

**Comment by danielmm8888** [comment]
Just extract it in your sourcemods folder and overwrite any files if you're asked to do so.
