### ISSUE TITLE
Game Crashes when trying to switch loadouts.

### ISSUE THREAD

**Issue by Ian502** [danielmm8888/TF2Classic#39]
I have to bind the command "toggle tf2c_weaponset_show" to a letter ( Because show inventory doesn't appear in my "Keyboard options" under "Team Fortress" category ) When I pick a class and press the button I binded to, for example with Pyro, I had no trouble (He has no weapons to switch to), but when I go to Scout's or Demoman's, game crashes and shuts down.

Just pointing out.

I installed first the 1.8.0 then the 1.8.3 hotfix directly, tell me if I have to install the "middle patches" manually, I did not use the autoupdater.

**Comment by tebjss** [comment]
Yeah I have the same issue, really hope this gets fixed soon since I haven't had the chance to try any of the new weapons yet

**Comment by Ian502** [comment]
The thing is, I was able to change weapons with the sniper, the thing crashes only when switching the scout and demoman weapons. (Haven't tried with heavy yet).

I eventried installing every patch in between the 1.8.0 and 1.8.3 (Including the 8.1 and 8.2 and their respective hotfixes)
