### ISSUE TITLE
in-game crash

### ISSUE THREAD

**Issue by maxdeelb4** [danielmm8888/TF2Classic#51]
i have an in-game crash 

whenever i try to play the game i crash

i was doing something on the game and im totally doomed

fix the bug 

thank you

**Comment by danielmm8888** [comment]
Could you explain the bug further? What were you doing when the crash happened?

**Comment by maxdeelb4** [comment]
Idk i was like playing the game and suddenly i crash you could view it what i had expeirenced

**Comment by maxdeelb4** [comment]
Ill try to make a video and ill show you

**Comment by Kapasky** [comment]
Could you please check for any memdumps that the game would have spat out after a crash. Is it a hard crash, or a soft crash?

**Comment by maxdeelb4** [comment]
well i could tell you that i also was lagging in the mean time

cuz my ping is so high idk why

is that a bug
