### ISSUE TITLE
No russian text in menus

### ISSUE THREAD

**Issue by xDShot** [danielmm8888/TF2Classic#64]
The menu entries are completely blank in main menu:

![2015-04-16_00002](https://cloud.githubusercontent.com/assets/4261659/7182075/b93a5594-e457-11e4-8f5e-4d13a43ae78a.jpg)

**Comment by xDShot** [comment]
Putting *tf2build.ttf* from team fortress 2 into mod did help me. So I guess it's needed to be updated in mod, so other locales might be fixed.

![2015-04-16_00003](https://cloud.githubusercontent.com/assets/4261659/7182362/7c8796dc-e459-11e4-8834-5484d18da852.jpg)

**Comment by Hasklet** [comment]
Thanks, we'll look into updating font files asap.
