### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by Kiwi-1995** [danielmm8888/TF2Classic#68]
As it stands the current Linux Binaries are broken. Server side it seems to be that segmentation fault that's causing it. With the client it's producing a much more severe error. 

http://pastebin.com/eTCTTiJf

^ is the error log coming straight from a terminal on Lubuntu (Ubuntu Utopic 14.10 64 Bit) with steam and the game running as root/Admin permissions.

The game is not giving off any MDMP files

**Comment by Kiwi-1995** [comment]
as a note if this is a pathing issue you can change what it is now to use ~/

~/ = userhome directory

~/.steam/steam/steamapps/common/Source SDK Base 2013 Multiplayer

would for me lead to /home/kiwi/.steam/steam/steamapps/common/Source SDK Base 2013 Multiplayer

**Comment by Outfl3sh** [comment]
looks like I have the same problem, getting segmentation faults both with integrated and dedicated video card so I guess it's something more general 

when I try to launch game directly from the game list it don't even bother displaing anything, but if I play *"Source SDK Base 2013 Multiplayer"* with parameters set to *-game "/home/st/.steam/steam/SteamApps/sourcemods/tf2classic"* then it segfaults in the loading screen, few seconds after the valve logo & stuff 

dump 1: http://ix.io/i4X (with nvidia optimus)
dump 2: http://ix.io/i4Z (with intel integrated card)
specs: http://ix.io/i52 (i don't think that'll help, but who knows)

**Comment by Th13teen** [comment]
This should be fixed with the latest 2.0.0b1 download.
