### ISSUE TITLE
DM - Minigun slowdown lasting forever

### ISSUE THREAD

**Issue by Walter20210** [danielmm8888/TF2Classic#81]
- Glitch found in 1.9 version -
When playing as a Mercenary if you pick up another primary weapon while spining up/shooting a minigun, the slowdown it applies will last forever until death or via picking up a minigun again and spining it up for a sec.

Before performing the glitch. (Speed equals to 250.0)
http://i.imgur.com/EsOrS5p.jpg

While spining up/shotting. (Speed equals to 80.0)
http://i.imgur.com/vlZGav2.jpg

After performing the glitch. Notice how the speed doesn't change.
http://i.imgur.com/sIvoRqJ.jpg
http://i.imgur.com/aAaVeSi.jpg

A possible fix for this could be:
Making players be unable to pickup weapons while shooting. (By doing so, the minigun would give the player back his original speed.)
Or either make these weapons give back the player 280 speed.

**Comment by Th13teen** [comment]
Fixed in 2.0.0b1.
