### ISSUE TITLE
server uses different class tables error

### ISSUE THREAD

**Issue by Alias23** [danielmm8888/TF2Classic#87]
Whenever I try to join a server, an error saying "server uses different class tables" comes up. I have the most recent patch installed.

**Comment by danielmm8888** [comment]
What does the patch number in the main menu say for you?

**Comment by Alias23** [comment]
i dont see a patch number anywhere in the main menu

**Comment by danielmm8888** [comment]
Go to the TF2Classic folder and open version.txt. What does it say?

**Comment by Alias23** [comment]
nvmd, rextracted the files and now it works fine

**Comment by Alias23** [comment]
nvmd spoke too soon, still having issues, icon art updated so i assumed everything was fine lol

**Comment by Alias23** [comment]
oh and the version.txt folder says 1.8.3.1

**Comment by danielmm8888** [comment]
The latest patch is 1.9.0

**Comment by Alias23** [comment]
oh ok, its not on the main download page

**Comment by danielmm8888** [comment]
That's because the person responsible for updating the page still hasn't done so in 2 weeks.
Here's the link.

http://www.mediafire.com/download/uvpkdeggp9qf5z9/Team_Fortress_2_Classic_1.8.0_(or_later)_to_1.9.0.7z

**Comment by Alias23** [comment]
its working fine now, thanks!
