### ISSUE TITLE
Players crashing on trying to join a server

### ISSUE THREAD

**Issue by 404UserNotFound** [danielmm8888/TF2Classic#9]
May or may not be related to the 4 team setup. I experienced this issue when trying to join a 4team block fortress server. Game would crash to desktop without any errors on "Sending client info..."

Using "connect <ip>" allowed me to connect without issue, but that may have been a fluke.

*This ticket has been submitted for easier issue tracking. Please close if the issue has been resolved.*

**Comment by LaylConway** [comment]
I'm encountering this problem as well, I can't join any server or even start a local game, it will always crash to desktop.
