### ISSUE TITLE
DM - Pipebomb launcher overrides new primary weapons, sorta

### ISSUE THREAD

**Issue by RevCosmosis** [danielmm8888/TF2Classic#93]
When you have the pipebomb launcher, picking up a new primary weapon will not replace it. You will be stuck with the pipebomb launcher. However, if you pick up a new secondary weapon, the pipebomb launcher will be replaced by whatever the last primary weapon was that you picked up.

For example: You pick up a pipebomb launcher. Then you pick up a flamethrower. You will still have the pipebomb launcher, and you cannot use the flamethrower. Next, you pick up an SMG. Your pipebomb launcher will then become a flamethrower.

**Comment by danielmm8888** [comment]
This has been fixed in 2.0.0b1
