### ISSUE TITLE
deathmatch mercenary model texture is messed up.

### ISSUE THREAD

**Issue by Suomimies55** [danielmm8888/TF2Classic#96]
http://i.imgur.com/LXmo5lv.jpg

http://i.imgur.com/SOiCJjL.jpg

No such variable "$yellow" for material "models/player/merc_deathmatch/merc_custom_alt"
Error: Material "models/player/merc_deathmatch/merc_custom_alt" : proxy "YellowLevel" unable to initialize!
No such variable "$yellow" for material "models/player/merc_deathmatch/merc_custom_alt"
Error: Material "models/player/merc_deathmatch/merc_custom_alt" : proxy "Multiply" unable to initialize!
*** Error unserializing VTF file... is the file empty?
Error reading material data "materials/models/player/merc_deathmatch/merc_alt_exp.vtf"
*** Error unserializing VTF file... is the file empty?
Error reading material data "materials/models/player/merc_deathmatch/merc_alt_bumpmap.vtf"
No such variable "$yellow" for material "models/player/merc_deathmatch/merc_custom_gib"
Error: Material "models/player/merc_deathmatch/merc_custom_gib" : proxy "YellowLevel" unable to initialize!
No such variable "$yellow" for material "models/player/merc_deathmatch/merc_custom_gib"
Error: Material "models/player/merc_deathmatch/merc_custom_gib" : proxy "Multiply" unable to initialize!
S

**Comment by NicknineTheEagle** [comment]
No longer relevant.
