### ISSUE TITLE
Crash joining/making server 

### ISSUE THREAD

**Issue by Crafter2000** [danielmm8888/TF2Classic#99]
As soon as i try to join a server it just crashes force closing the client ATM i am using version 1.9.0
i used the auto updater to update the pack from the base client version 1.0.0 to 1.9.0

**Comment by PistonMiner** [comment]
Can you upload the dump issued with the crash please? You can find it in /Steam/dumps immediately after crashing. Its unreliable though, so sometimes it might not create a dump.

**Comment by Crafter2000** [comment]
https://www.dropbox.com/s/qewk5t0xjfhqy23/crash_hl2.exe_20150530213847_1.dmp?dl=0
Here you can take a look at it. it says i am missing stuff as far as i can tell
